#!/bin/bash
#shellcheck disable=SC2155,SC1091
set -euo pipefail

declare PRG0=$(readlink -en -- "$0")
declare PRGDIR=$(dirname "$PRG0")
declare PRG=$(basename "$PRG0")
    
#source "$PRGDIR"/.venv/bin/activate

"$PRGDIR"/"$PRG".py "$@"

#fin
